import type { NextPage } from 'next'
import Head from 'next/head'

import AboutUs from '../containers/AboutUs'
import ContactUs from '../containers/ContactUs'
import ProjectShowcase from '../containers/ProjectShowcase'
import ImageShowcase from '../containers/ImageShowcase'
import Service from '../containers/Service'
import DesktopFrame from '../components/templates/DesktopFrame'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>0xBlanc.io - HK Web3 Solution Provider</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/logo512.png' />
        <meta name='googlebot' content='noindex,nofollow' />
        <meta property='og:image' content='/logo512.png' />
      </Head>
      <DesktopFrame>
        <div className='flex flex-col'>
          <AboutUs />
          <Service />
          <ImageShowcase />
          <ProjectShowcase />
          <ContactUs />
        </div>
      </DesktopFrame>
    </>
  )
}

export default Home
